### PR TITLE
I9500: Fix root in recovery, update prebuilt kernel

### PR DESCRIPTION
**Pull request by Faryaab**
Freshly compiled prebuilt kernel from GT-I9500_JB_Opensource_Update1

### CODE REVIEW

**Comment by cm-gerrit** [comment]
Hi there;

This is an automated reply, to let you know CyanogenMod doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at http://review.cyanogenmod.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.cyanogenmod.org/wiki/Howto:_Gerrit

Thanks!

**Comment by Faryaab** [comment]
Don't merge, yet. Need to enable Touchscreen in kernel too.

**Comment by koush** [comment]
How does this fix root in recovery?

The root in recovery problem is due to your adb_keys I think.

**Comment by Faryaab** [comment]
After building the recovery with the new kernel the root worked.

The thing was that previously the kernel was taken from the stock recovery image and Samsung has set restrictions on root in the kernel thus was not letting us obtain root in recovery. The new kernel has been compiled with those restrictions disabled.

**Comment by thuy4mua** [comment]
Thanks

**Pull request closed without merging**
