### PR TITLE
Fix CM build

### PR DESCRIPTION
**Pull request by Faryaab**

### CODE REVIEW

**Comment by cm-gerrit** [comment]
Hi there;

This is an automated reply, to let you know CyanogenMod doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at http://review.cyanogenmod.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.cyanogenmod.org/wiki/Howto:_Gerrit

Thanks!

**Comment by codeworkx** [comment]
Take this as ref:
https://github.com/CyanogenMod/android_device_lge_mako/blob/cm-10.1/full_mako.mk
https://github.com/CyanogenMod/android_device_lge_mako/blob/cm-10.1/device.mk

**Comment by Faryaab** [comment]
Okay. Thanks!  :-)

**Comment by koush** [comment]
don't think this is even in gerrit yet, i just forked it.

**Pull request merged**
